config/routes.rb
Rails.application.routes.draw do

  devise_for :sessions
  devise_for :users
  resources :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope '/api' do
    resources :jobs
  end

	get '*path', to: "application#fallback_index_html", constraints: ->(request) do
	  !request.xhr? && request.format.html?
	end

end

app/models/job.rb
class Job < ApplicationRecord
	validates :position, :company, :location, :description, :salary, :presence => true
	belongs_to :user
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = Job.all

    render json: @jobs
  end

  def show
    render json: @job
  end

  def create
      @job = Job.new(job_params)
      if @job.save 
          render json: @job, status: :created, location: @job
      else
          render :json => { :errors => @job.errors.full_messages }, :status => 422
      end
  end

  def update
    if @job.update(job_params)
      render json: @job
    else
      render :json => { :errors => @job.errors.full_messages }, :status => 422
    end
  end

  def destroy
    @job.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:user_id, :position, :company, :location, :lat, :lng, :description, :salary)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position, id: :job_position %>
  </div>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, id: :job_company %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, id: :job_location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :job_description %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.text_field :salary, id: :job_salary %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Position</th>
      <th>Company</th>
      <th>Location</th>
      <th>Description</th>
      <th>Salary</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.position %></td>
        <td><%= job.company %></td>
        <td><%= job.location %></td>
        <td><%= job.description %></td>
        <td><%= job.salary %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Position:</strong>
  <%= @job.position %>
</p>

<p>
  <strong>Company:</strong>
  <%= @job.company %>
</p>

<p>
  <strong>Location:</strong>
  <%= @job.location %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @job.salary %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>